### PR TITLE
Update gcc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 48166757dcf4

### CODE REVIEW

**Comment by mscastanho** [comment]
glibc stage 1 failed: 
```
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
    8 | DECL_ALIAS_s_modf (modf);
      | ^~~~~~~~~~~~~~~~~
make[3]: *** [../o-iterator.mk:9: /home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_ldexpf128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
    8 | DECL_ALIAS_s_ldexp (ldexp);
      | ^~~~~~~~~~~~~~~~~~
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_frexpf128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
    8 | DECL_ALIAS_s_frexp (frexp);
      | ^~~~~~~~~~~~~~~~~~
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_ldexpf128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
make[3]: *** [../o-iterator.mk:9: /home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_frexpf128-ifunc.o] Error 1
make[3]: *** [../o-iterator.mk:9: /home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_ldexpf128-ifunc.o] Error 1
/home/tcbot/bot-worker/at/src/at15.0-0-alpha.ubuntu-20_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
    8 | DECL_ALIAS_s_modf (modf);
```
However, I couldn't find a clue about which GCC commit started to trigger this.

**Comment by mscastanho** [comment]
I isolated one of the failing commands from the log:
```
/home/mscastanho/AT/gcc-broken-ifunc128/opt/at-next-15.0-0-alpha/bin/gcc -m64 /home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.c -c -std=gnu11 -fgnu89-inline  -g -O2 -msecure-plt -fcommon -Wno-error=stringop-overread -Wall -Wwrite-strings -Wundef -Werror -fmerge-all-constants -frounding-math -fno-stack-protector -Wstrict-prototypes -Wold-style-definition -fmath-errno -mabi=ieeelongdouble -Wno-psabi -mno-gnu-attribute -mlong-double-128  -fpic   -ftls-model=initial-exec   -mabi=ibmlongdouble     -I../include -I/home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math  -I/home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/le/fpu  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/fpu  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64/le  -I../sysdeps/unix/sysv/linux/powerpc/powerpc64  -I../sysdeps/unix/sysv/linux/wordsize-64  -I../sysdeps/unix/sysv/linux/powerpc  -I../sysdeps/powerpc/nptl  -I../sysdeps/unix/sysv/linux/include -I../sysdeps/unix/sysv/linux  -I../sysdeps/nptl  -I../sysdeps/pthread  -I../sysdeps/gnu  -I../sysdeps/unix/inet  -I../sysdeps/unix/sysv  -I../sysdeps/unix/powerpc  -I../sysdeps/unix  -I../sysdeps/posix  -I../sysdeps/powerpc/powerpc64/le/power8/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/power7/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/fpu/multiarch  -I../sysdeps/powerpc/powerpc64/le/power8/fpu  -I../sysdeps/powerpc/powerpc64/le/power7/fpu  -I../sysdeps/powerpc/powerpc64/le/fpu  -I../sysdeps/powerpc/powerpc64/fpu  -I../sysdeps/powerpc/powerpc64/le/power8/multiarch  -I../sysdeps/powerpc/powerpc64/le/power7/multiarch  -I../sysdeps/powerpc/powerpc64/le/multiarch  -I../sysdeps/powerpc/powerpc64/multiarch  -I../sysdeps/powerpc/powerpc64/le/power8  -I../sysdeps/powerpc/powerpc64/power8  -I../sysdeps/powerpc/powerpc64/le/power7  -I../sysdeps/powerpc/powerpc64/power7  -I../sysdeps/powerpc/powerpc64/power6  -I../sysdeps/powerpc/powerpc64/power4  -I../sysdeps/powerpc/power4  -I../sysdeps/powerpc/powerpc64/le  -I../sysdeps/powerpc/powerpc64  -I../sysdeps/wordsize-64  -I../sysdeps/powerpc/fpu  -I../sysdeps/powerpc  -I../sysdeps/ieee754/ldbl-128ibm-compat  -I../sysdeps/ieee754/ldbl-128ibm/include -I../sysdeps/ieee754/ldbl-128ibm  -I../sysdeps/ieee754/ldbl-opt  -I../sysdeps/ieee754/dbl-64  -I../sysdeps/ieee754/flt-32  -I../sysdeps/ieee754/float128  -I../sysdeps/ieee754  -I../sysdeps/generic  -I.. -I../libio -I. -nostdinc -isystem /home/mscastanho/AT/gcc-broken-ifunc128/opt/at-next-15.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/12.0.0/include -isystem /home/mscastanho/AT/gcc-broken-ifunc128/opt/at-next-15.0-0-alpha/lib/gcc/powerpc64le-linux-gnu/12.0.0/include-fixed -isystem /home/mscastanho/AT/gcc-broken-ifunc128/opt/at-next-15.0-0-alpha/include  -D_LIBC_REENTRANT -include /home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/libc-modules.h -DMODULE_NAME=libc -include ../include/libc-symbols.h  -DPIC -DSHARED     -DTOP_NAMESPACE=glibc -I../soft-fp -o /home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.os -MD -MP -MF /home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.os.dt -MT /home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.os
/home/mscastanho/AT/gcc-broken-ifunc128/build/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/builds/glibc_1-64/math/s_modff128-ifunc.c:8:1: error: ‘-mabi=ibmlongdouble’ requires ‘-mlong-double-128’
    8 | DECL_ALIAS_s_modf (modf);
```
Notice that `-mlong-double-128` was used, but the error still happens.

**Comment by tuliom** [comment]
My bisect is pointing at:
```
ebd5e86c0f41dc1d692f9b2b68a510b1f6835a3e is the first bad commit
commit ebd5e86c0f41dc1d692f9b2b68a510b1f6835a3e
Author: Martin Liska <mliska@suse.cz>
Date:   Wed Mar 10 15:12:31 2021 +0100
    Improve global state for options.
    gcc/c-family/ChangeLog:
            PR tree-optimization/92860
            PR target/99592
            * c-attribs.c (handle_optimize_attribute): Save target node
            before calling parse_optimize_options and save it in case
            it changes.
            * c-pragma.c (handle_pragma_target): Similarly for pragma.
            (handle_pragma_pop_options): Likewise here.
    gcc/ChangeLog:
            PR tree-optimization/92860
            PR target/99592
            * optc-save-gen.awk: Remove exceptions.
 gcc/c-family/c-attribs.c |  9 +++++++++
 gcc/c-family/c-pragma.c  | 16 ++++++++++++----
 gcc/optc-save-gen.awk    |  9 ---------
 3 files changed, 21 insertions(+), 13 deletions(-)
 ```

**Comment by tuliom** [comment]
The issue has been reported upstream: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100909

**Comment by mscastanho** [comment]
@tuliom I think we could create a separate issue for this and close this PR so Cherbot can open a new one tomorrow. At least that way we test it with a newer revision. What do you think?

**Comment by tuliom** [comment]
> @tuliom I think we could create a separate issue for this and close this PR so Cherbot can open a new one tomorrow. At least that way we test it with a newer revision. What do you think?

@mscastanho I have no objections to closing this PR, but I tested another build with a commit ID from today and the issue is still there. So, I don't think that having new tests would help.
You might prefer to track the GCC bug and close this PR after a fix is merged...

**Comment by mscastanho** [comment]
I'm fine with that :+1:

**Comment by mscastanho** [comment]
Yesterday I tested reverting the GCC patch pointed by @tuliom, but using the latest GCC revision causes another build failure:
```
libstdc++-v3/include/mutex:622:17: error: there are no arguments to ‘__gthread_yield’ that depend on a template parameter, so a declaration of ‘__gthread_yield’ must be available [-fpermissive]
  622 |                 __gthread_yield();
```

I already sent [a patch to libstdc++](https://gcc.gnu.org/pipermail/libstdc++/2021-June/052858.html) to fix this issue and it has been approved, should land upstream later today. Then I'll try again with the new revision.
