### PR TITLE
Update glibc on AT next

### PR DESCRIPTION
**Pull request by Cherbot**
Bump to revision 04bba1e5d84b

### CODE REVIEW

**Comment by mscastanho** [comment]
binutils stage 2 failed:
```
/home/tcbot/bot-slave/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc: In function ‘int main(int, char**)’:
/home/tcbot/bot-slave/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc:294:36: error: ‘mallinfo mallinfo()’ is deprecated [-Werror=deprecated-declarations]
  294 |       struct mallinfo m = mallinfo();
      |                                    ^
In file included from /home/tcbot/bot-slave/at/src/at15.0-0-alpha.redhat-8_ppc64le_ppc64le/sources/binutils/gold/main.cc:29:
/home/tcbot/bot-slave/at_opt/at-next-15.0-0-alpha/include/malloc.h:118:24: note: declared here
  118 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
```

This was caused by the recent deprecation of `mallinfo` on glibc:
```
commit 30e5069c7d4b51288d3e6f75f53a6ad2f5e71b0f
Author: Adhemerval Zanella <adhemerval.zanella@linaro.org>
Date:   Mon Aug 31 11:14:01 2020 -0300

    malloc: Fix mallinfo deprecation declaration
    
    It fixes the build issue below introduced by e3960d1c57e57 (Add
    mallinfo2  function that support sizes >= 4GB).  It moves the
    __MALLOC_DEPRECATED to the usual place for function attributes:
    
      In file included from ../include/malloc.h:3,
                       from ../sysdeps/x86_64/multiarch/../../../test-skeleton.c:31,
                       from ../sysdeps/x86_64/multiarch/test-multiarch.c:96:
      ../malloc/malloc.h:118:1: error: empty declaration [-Werror]
        118 | __MALLOC_DEPRECATED;
    
    It also adds the required deprecated warning suppression on the tests.
    
    Checked on x86_64-linux-gnu.

commit e3960d1c57e57f33e0e846d615788f4ede73b945
Author: Martin Liska <mliska@suse.cz>
Date:   Tue Jul 7 13:58:24 2020 +0200

    Add mallinfo2 function that support sizes >= 4GB.
    
    The current int type can easily overflow for allocation of more
    than 4GB.

```

**Comment by mscastanho** [comment]
Filed issue upstream: [BZ#26585](https://sourceware.org/bugzilla/show_bug.cgi?id=26585)
