### ISSUE TITLE
Remove -Wno-error=stringop-overread from glibc stage 1

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#1876]
This was required to successfully build #1875. That set of GCC commits (`e87559d202d9..151d1347c99a`) introduced the following warning (only) when building glibc stage 1:

```
In function ‘__rawmemchr_ppc’,
    inlined from ‘__rawmemchr_ppc’ at ../string/rawmemchr.c:27:1:
../string/rawmemchr.c:40:12: error: ‘memchr’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overread]
   40 |     return memchr (s, c, (size_t)-1);

```

Note this issue has already been fixed on glibc upstream by commit `3357087b2a9` by using a `#pragma` (hidden behind `DIAG_IGNORE_NEEDS_COMMENT`) to ignore this specific warning, which is a false positive. However, it looks like one of the gcc commits in the range introduced by #1875 caused a change in the preprocessor behaviour that is causing this `#pragma` directive to be completely ignored. 

I still don't know if that is a gcc bug or if we are now missing some more configuration for gcc stage 1 (used to compile glibc stage 1), since this only happens on glibc stage 1 and not on the others, which use gccs built on later stages.

**Comment by mscastanho** [comment]
Turns out the issue also happens on other glibc stages on native builds.

**Comment by tuliom** [comment]
This issue has been reported in upstream GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98512

**Comment by tuliom** [comment]
The GCC fix has been deferred to GCC 12.

**Comment by mscastanho** [comment]
Looks like this has been [fixed upstream](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=6d3bab5d5adb3e28ddb16c97b0831efdea23cf7d). We may be able to remove this flag once #2241 gets merged (update that includes that gcc commit).
